- hosts: all
  tasks:
   - name: setting up jenkins repo
     yum_repository:
       name: jenkins
       description: Jenkins-stable
       baseurl: https://pkg.jenkins.io/redhat-stable
       gpgcheck: 0

   - name: downloading jenkins key
     rpm_key:
       key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
       state: present

   - name: updating yum
     yum:
       name: yum
       state: latest

   - name: installing openjdk software
     yum:
       name: "java-1.8.0-openjdk-devel"
       state: present
       
       
   - name: installing jenkins software
     yum:
       name: jenkins
       state: present

   - name: start the service
     service:
       name: jenkins
       state: started
